version: '3.7'

services:
  elassandra:
    image: strapdata/elassandra:6.8.4.3
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "DEBUG=true"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - "9042:9042"
      - "9200:9200"
    volumes:
      - /var/lib/cassandra/data:/var/lib/cassandra/data
      - /etc/cassandra/conf:/etc/cassandra

  gluster:
    image: gluster/gluster-centos:gluster4u0_centos7
    ports:
      - "24007:24007"
      - "24008:24008"
      - "49152:49152"
      - "2049:2049"
    restart: unless-stopped
    volumes:
      - /etc/glusterfs:/etc/glusterfs:z
      - /var/lib/glusterd:/var/lib/glusterd:z
      - /var/log/glusterfs:/var/log/glusterfs:z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/:/dev
      - /data/brick1/gv0:/data/brick1/gv0

  yamka:
    image: yamka/backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "1746:1746"
      - "1747:1747/udp"
    links:
      - elassandra
    restart: unless-stopped
    volumes:
      - /var/log/yamka:/var/log/yamka
      - /data/brick1/gv0/file_storage:/data/brick1/gv0/file_storage
    depends_on:
      - elassandra
      - gluster
    secrets:
      - tls_fullchain
      - tls_privkey
      - cassandra_password
      - smtp_pass

networks:
  default:
    driver: "overlay"

secrets:
  tls_fullchain:
    file: ~/fullchain.pem
  tls_privkey:
    file: ~/privkey.pem
  cassandra_password:
    file: ~/cassandra_password
  smtp_pass:
    file: ~/smtp_pass