version: '3.7'

services:
  scylla:
    image: scylladb/scylla:4.3.6
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - 9042:9042
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9160:9160
      - 9180:9180
      - 10000:10000
    volumes:
      - /var/lib/scylla:/var/lib/scylla
      - /etc/scylla:/etc/scylla

  yamka:
    image: yamka/backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1746:1746
      - 1747:1747/udp
    links:
      - scylla
    restart: unless-stopped
    volumes:
      - /var/log/yamka:/var/log/yamka
      - /data/brick1/gv0/file_storage:/data/brick1/gv0/file_storage
    depends_on:
      - scylla
    secrets:
      - tls_fullchain
      - tls_privkey
      - cassandra_password
      - smtp_pass

secrets:
  tls_fullchain:
    file: ~/fullchain.pem
  tls_privkey:
    file: ~/privkey.pem
  cassandra_password:
    file: ~/cassandra_password
  smtp_pass:
    file: ~/smtp_pass